name: Continuous Integration (CI)

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Java toolchain
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Run unit tests
        run: ./gradlew test
