name: PMD Code Analysis

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          version: 7.0.0-rc4
          rulesets: rulesets/java/quickstart.xml
          sourcePath: src
          uploadSarifReport: true

      - name: Upload PMD results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pmd-results
          path: pmd-results.sarif
