name: PMD Code Analysis

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run PMD
        uses: pmd/pmd-github-action@d9c1f3c5940cbf5923f1354e83fa858b4496ebaa
        with:
          version: 7.0.0-rc4
          rulesets: rulesets/java/quickstart.xml
          sourcePath: src/main
          uploadSarifReport: true
          analyzeModifiedFilesOnly: false

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0
        with:
          sarif_file: pmd-report.sarif
